{% set name = "pynisher" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/automl/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9b36cb0598d527b074456d02385a336ec40aeb0047dd68894b169c2a6a97304c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # version 0.6.4 is very old and does not support Windows
  # (introduced in version 1.0.0)
  skip: True  # [py<37 or win]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - psutil
    - python
    - typing_extensions
    - pywin32  # [win]

# skipping some tests that seem to play with timeouts and number of process and
# they fail, not sure why, but they seem not failing for a packaging reason.
{% set tests_to_skip = "" %}
{% set tests_to_skip = tests_to_skip + "test_num_processes" %}
{% set tests_to_skip = tests_to_skip + " or test_out_of_memory" %}
{% set tests_to_skip = tests_to_skip + " or test_kill_subprocesses" %}
{% set tests_to_skip = tests_to_skip + " or test_liblinear_svc" %}
{% set tests_to_skip = tests_to_skip + " or test_too_little_memory" %}
{% set tests_to_skip = tests_to_skip + " or test_raise" %}  # [osx]
{% set tests_to_skip = tests_to_skip + " or test_busy_in_C_library" %}  # [osx]

test:
  imports:
    - pynisher
  requires:
    - pip
    - pytest
    - scikit-learn
  source_files:
    - test
  commands:
    - pip check
    - pytest -v . -k "not ({{ tests_to_skip }})"


about:
  home: https://github.com/automl/pynisher
  summary: A small Python library to limit the resources used by a function by executing it inside a subprocess.
  description: |
    The pynisher is a little module intended to limit a functions resources. It starts a new process, sets the desired limits,
    and executes the function inside it. In the end, it returns the function return value. If, for any reason,
    the function call is not successful, None is returned.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/automl/pynisher
  doc_url: https://github.com/automl/pynisher/blob/main/README.md

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
